---

kind: pipeline
type: docker
name: lint:backend

depends_on: []

steps:
  - name: lint:flake8
    image: alpine/flake8:3.9.0
    commands:
      - cd backend
      - flake8 ./

  - name: lint:black
    image: kiwicom/black:20.8b1
    commands:
      - cd backend
      - black --check --diff ./

trigger:
  changeset:
    includes:
      - backend/**
  branch:
    - master
    - feat/*
